# Setup
title: "Pedro Franceschi"
description: "I'm the true in your while loop. In other words, I write code."
url: "http://blog.pedro.io"
baseurl: '/'
paginate: 5

# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty
